import Head from "next/head";
import { LayoutContainer, Navbar } from "../src/components/index";
import NavItems from "../src/utils/navitems";
export default function Home() {
  return (
    <LayoutContainer>
      <Head>
        <title>NaturalTaste</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/svg+xml" href="favicon.svg" />
      </Head>
      <Navbar items={NavItems} />
    </LayoutContainer>
  );
}
