import Head from "next/head";
import { LayoutContainer } from "../src/components/index";
export default function Home() {
  return (
    <Head>
      <title>NaturalTaste</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" type="image/svg+xml" href="favicon.svg" />
    </Head>
  );
}
